export const productos = [
    { id: 1, titulo: "Conjunto Deportivo", categoria: "hombre", imagen: "./conjuntodeportivo.png", },
    { id: 2, titulo: "Franelillas", categoria: "hombre", imagen: "./franelilla.png", },
    { id: 3, titulo: "Franela 100% Algodon", categoria: "hombre", imagen: "./franela100.png", },
    { id: 4, titulo: "Camisa Poliester", categoria: "hombre", imagen: "./camisapoliester.png", },
    { id: 5, titulo: "Licra Dama", categoria: "dama", imagen: "./calzadama.png", },
    { id: 6, titulo: "Camisa Dama", categoria: "dama", imagen: "./remeradama.png", },
    { id: 7, titulo: "Top Dama", categoria: "dama", imagen: "./topdama.png", },
    { id: 8, titulo: "Chaqueta Dama", categoria: "dama", imagen: "./camperadama.png", },
    { id: 9, titulo: "Chaqueta Niño", categoria: "niño", imagen: "./camperaniño.png", },
    { id: 10, titulo: "Jogger Dama", categoria: "dama", imagen: "./joggerdama.png", },
    { id: 11, titulo: "Bolso Dama", categoria: "dama", imagen: "./mochiladama.png", },
    { id: 12, titulo: "Chaqueta Impermeable", categoria: "hombre", imagen: "./chaquetaimpermeable.png", },
    { id: 13, titulo: "Uniforme Deportivo", categoria: "hombre", imagen: "./uniformedeportivo.png", },
    { id: 14, titulo: "Jogger Caballero", categoria: "hombre", imagen: "./jogger.png", },
    { id: 15, titulo: "Bolso Niño", categoria: "niño", imagen: "./mochilaniño.png", },
    { id: 16, titulo: "Sueter Niño", categoria: "niño", imagen: "./buzoniño.png", },
    { id: 17, titulo: "Jogger Niño", categoria: "niño", imagen: "./joggerniño.png", },
    { id: 18, titulo: "Franelilla Niño", categoria: "niño", imagen: "./musculosaniño.png", },
    { id: 19, titulo: "Gorra Niño", categoria: "niño", imagen: "./gorraniño.png", },
    { id: 20, titulo: "Camison Dama", categoria: "dama", imagen: "./remerondama.png", },
    { id: 21, titulo: "Sueter Dama", categoria: "dama", imagen: "./buzodama.png", },
    { id: 22, titulo: "Lenceria Dama", categoria: "dama", imagen: "./lenceriadama.png", },
    { id: 23, titulo: "Franelilla Dama", categoria: "dama", imagen: "./musculosadama.png", },
    { id: 24, titulo: "Boxers", categoria: "hombre", imagen: "./ropainteriorhombre.png", },
];

